[package]
name = "map_enum_generic_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["derive", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"